# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-09 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import myimagetest.models


class Migration(migrations.Migration):

    dependencies = [
        ('myimagetest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('video', models.FileField(upload_to=myimagetest.models.upload_location)),
            ],
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
